name: "Checksum"
inputs:
  directory:
    description: "Directory to checksum"
    required: true
  outputFile:
    description: "Output checksum to file"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checksum directory
      shell: bash
      run: |
        find ${{ inputs.directory }} -type f -exec md5sum {} + \
          | awk '{print $1}' \
          | sort \
          | md5sum \
          > ${{ inputs.outputFile }}
